tools:
    php_sim: true
    php_pdepend: true
    php_analyzer: true
    php_cs_fixer:
        config: { level: psr2 }
    sensiolabs_security_checker: true
    php_code_sniffer:
        config:
            standard: "PSR2"

filter:
    paths:
        - 'src/*'

build_failure_conditions:
    - 'elements.rating(< C).new.exists'
    - 'issues.label("coding-style").new.exists'
    - 'issues.severity(>= MAJOR).new.exists'
    - 'project.metric("scrutinizer.quality", < 9)'
