sudo: false

language: php

php:
  - '7.2'

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer install --prefer-source --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
